service:
  name: standup-bot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  env: ${file(./${opt:stage, self:provider.stage}.env.json)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3000

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  check-standup:
    handler: handle-standupbot.checkStandup
    events:
      - schedule:
          rate: cron(00 19 ? * MON,WED,FRI *) # ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
          enabled: true
      - schedule:
          rate: cron(30 17 ? * MON,WED,FRI *) # ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
          enabled: true
    environment:
      SLACK_KEY: ${self:custom.env.SLACK_KEY}
      SLACK_STANDUP_CHANNEL: ${self:custom.env.SLACK_STANDUP_CHANNEL}
      REMOVE_FROM_STANDUP: ${self:custom.env.REMOVE_FROM_STANDUP}
  prompt-standup:
    handler: handle-standupbot.promptStandup
    events:
      - schedule:
          rate: cron(0 17 ? * MON,WED,FRI *) # ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions
          enabled: true
    environment:
      SLACK_KEY: ${self:custom.env.SLACK_KEY}
      SLACK_STANDUP_CHANNEL: ${self:custom.env.SLACK_STANDUP_CHANNEL}
      REMOVE_FROM_STANDUP: ${self:custom.env.REMOVE_FROM_STANDUP}
  list-standup-users:
    handler: handle-standupbot.listStandupUsers
    environment:
      SLACK_KEY: ${self:custom.env.SLACK_KEY}
      SLACK_STANDUP_CHANNEL: ${self:custom.env.SLACK_STANDUP_CHANNEL_PROD}
      REMOVE_FROM_STANDUP: ${self:custom.env.REMOVE_FROM_STANDUP}
  

#0 20 * * * /usr/share/meowbot/dadjokes.pl
#0 14 * * 2 /usr/share/meowbot/crazytweet.pl iamdevloper Dev
#0 14 * * 5 /usr/share/meowbot/crazytweet.pl CrazyMgmtCons Consulting